### ISSUE TITLE
package-lock.json included with repo

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify-nextjs#238]
Should `package-lock.json` be included with this repo?

As recommended by @mcollina https://github.com/fastify/fluent-json-schema/pull/91#pullrequestreview-570606419 and [Snyk](https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/) they pose a security risk.

If it does need to be included, we could add linting for it to the CI with [lockfile-lint](https://github.com/lirantal/lockfile-lint)

**Comment by mcollina** [comment]
It's needed as next and dependencies ship breaking changes in minor/patch releases.

**Comment by Fdawgs** [comment]
> 
> 
> It's needed as next and dependencies ship breaking changes in minor/patch releases.

Cheers, thanks for clarifying @mcollina
