### ISSUE TITLE
Next.js 11

### ISSUE THREAD

**Issue by uipoet** [fastify/fastify-nextjs#279]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.18.0

### Plugin version

5.4.1

### Node.js version

14.7.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

NixOS

### Description

```shell
❯ npm install                    
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: next@11.0.0
npm ERR! node_modules/next
npm ERR!   next@"11.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"9.x.x || 10.x.x" from fastify-nextjs@5.4.1
npm ERR! node_modules/fastify-nextjs
npm ERR!   fastify-nextjs@"5.4.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Steps to Reproduce

1. update `next` to `11.0.0` in `package.json`
1. `npm install`

### Expected Behavior

No error and no regressions.

**Comment by mcollina** [comment]
You need to update both the peerDependencies and the devDependencjes.

**Comment by uipoet** [comment]
Isn't the issue that `fastify-nextjs` has a peer dependency on on `next` locked to v10?

**Comment by mcollina** [comment]
Yes, it needs to be updated in both places. Would you like to send a PR?

**Comment by uipoet** [comment]
Happy to, though won't have availability until next week.

**Comment by uipoet** [comment]
Thank you for the prompt update!
