### ISSUE TITLE
start failed after add tailwind

### ISSUE THREAD

**Issue by Raz-Tw** [fastify/fastify-nextjs#300]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.6.0

### Plugin version

3.0.0

### Node.js version

14.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.4

### Description

after add tailwind to css file,
the `npm run dev` start failed

![image](https://user-images.githubusercontent.com/56281434/125180628-b7812800-e22e-11eb-8bad-4d0ef2aed1f4.png)

### Steps to Reproduce

i created repository [https://github.com/Raz-Tw/fastify-nextjs](https://github.com/Raz-Tw/fastify-nextjs)

the last commit

### Expected Behavior

normally start into dev mode

**Comment by mcollina** [comment]
Unfortunately tailwind takes too much time to compile, you need to increase the `pluginTimeout`:

```

@@ -1,10 +1,13 @@
 'use strict'

-const fastify = require('fastify')()
+const fastify = require('fastify')({
+  pluginTimeout: 30000
+})

 fastify
   .register(require('./index'))
-  .after(() => {
+  .after((err) => {
+    console.log(err)
     fastify.next('/hello')
   })
```
