### ISSUE TITLE
`fastify.next is not a function` when running `NODE_ENV=production`

### ISSUE THREAD

**Issue by mzegar** [fastify/fastify-nextjs#338]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.2

### Plugin version

6.0.0

### Node.js version

16.6.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04.2

### Description

Exactly similar to this https://github.com/fastify/fastify-nextjs/issues/88#issuecomment-875238776

```
    fastify.next('/hello')
            ^

TypeError: fastify.next is not a function
```
occurs if my `NODE_ENV` is set to `production`. Changing increasing the `pluginTimeout` doesn't fix it. Setting my `NODE_ENV` to `development` does.

### Steps to Reproduce

1. Setup the basic `fastify-nextjs` example found in the readme
2. Run with `NODE_ENV` set to production
3. Issue occurs

**Comment by climba03003** [comment]
Please `build` the next project before starting `fastify` in production.
AFAIK, it is what `nextjs` required for production mode.
