### ISSUE TITLE
`req` object in `getServerSideProps` is not updating whenever the page is revisited

### ISSUE THREAD

**Issue by mkhoussid** [fastify/fastify-nextjs#353]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm using [fastify-nextjs](https://github.com/fastify/fastify-nextjs) and here is my `server.js`:
```
const fastify = require('fastify')()
const fastifyCookie = require('fastify-cookie')
const fastifyServerSession = require('fastify-server-session')

fastify.register(fastifyCookie);

fastify
  .register(require('fastify-nextjs'))
  .after(() => {
	fastify.next('/', (app, req, reply) => {
		app.render(req.raw, reply.raw, '/', req.query);
	})
  })

fastify.listen(3000, err => {
  if (err) throw err
  console.log('Server listening on http://localhost:3000')
})
```
I also have an API route `init`:
```
exports.init = async function (request, reply) {
	try {
		const date = new Date();
		const nextMonthDate = date.setDate(date.getDate() + 30);

		reply.setCookie('hello', 'world', { expires: nextMonthDate });

                console.log('cookie in init', request.headers.cookie); // properly always prints 'hello=world; _ga=GA1.1.145480481.1604842511; _ym_uid=1604842511951463416; _ym_d=1604842511'

		return reply.send();
	} catch (err) {
		return reply.code(500).send();
	}
};
```
In my `index` page, I have the following content:
```
import React from 'react';
import { GetServerSideProps } from 'next';

const Index = React.memo(({ Component, ...pageProps }: AppProps) => {
	return <div>{'index page'}</div>;
});

export default Index;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
	const cookies = ctx.req.headers.cookie; // always prints '_ga=GA1.1.145480481.1604842511; _ym_uid=1604842511951463416; _ym_d=1604842511'

        console.log('cookie in getServerSideProps', cookies)

	console.log('cookies', cookies);

	return {
		props: {}
	};
};
```
`setCookies` properly sets it, but `getServerSideProps` never catches it.

What am I doing wrong here?

**Comment by climba03003** [comment]
`fastify-nextjs` pass the raw `Request` and `Response` object to `nextjs`. 
All the method dealing with `fastify` own `Request` or `Reply` object will not be reflected to the raw one.

**Comment by mkhoussid** [comment]
So are you saying it's impossible to access/pass the cookies to `getServerSideProps`?

**Comment by climba03003** [comment]
> 
> 
> So are you saying it's impossible to access/pass the cookies (or anything else) to `getServerSideProps`?
> 
> What if I also wanted to pass down a `redis` instance? Would I have to do this?
> 
> ```
> fastify.next('/cart', (app, req, reply) => {
> 	req.raw.redis = fastify.redis;
> 	app.render(req.raw, reply.raw, '/', req.query);
> });
> ```

You need to map the `req` and `req.raw` to reflect the changes. Yes, if pass it like this you can access the redis instance.

**Comment by mkhoussid** [comment]
> You need to map the fields you want from `req` to `req.raw` in order to reflect the changes. 

I've tried that already:

```
fastify.next('/', (app, req, reply) => {
	console.log('cookies', req.headers.cookies); // key 'hello' is missing; always prints: '_ga=GA1.1.145480481.1604842511; _ym_uid=1604842511951463416; _ym_d=1604842511'
	req.raw.redis = fastify.redis; // this works, I can access 'redis' in getServerSideProps
        req.raw.cookies = req.headers.cookies;
	app.render(req.raw, reply.raw, '/', req.query);
});
```

**Comment by climba03003** [comment]
Are you using `localhost` to test? If yes, please refer to this issue https://github.com/fastify/fastify-cookie/issues/140

**Comment by mkhoussid** [comment]
Thanks!
