### ISSUE TITLE
Add option to set Cache Duration for _next files

### ISSUE THREAD

**Issue by dunklesToast** [fastify/fastify-nextjs#368]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It would be awesome if we could set a custom cache duration for the files under the `_next` path. It seems to be 1d per default, but I haven't found any solution to increase this.

### Motivation

Since Next.JS adds content hashes into the name, it would be great if we can increase the cache duration to improve the page performance.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by climba03003** [comment]
The cache is actual set by `nextjs` itself. I think the user should follow the document from `nextjs`.

https://nextjs.org/docs/going-to-production#caching
