### ISSUE TITLE
TypeError: fastify.next is not a function

### ISSUE THREAD

**Issue by sbfkcel** [fastify/fastify-nextjs#384]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.0

### Plugin version

6.0.0

### Node.js version

14.15.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

I found that the plugin was not executed after preparation.

app.prepare().then(()=>{
       // Not performed
})

### Steps to Reproduce

package.json

```
"scripts": {
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js",
    "lint": "next lint"
  },
"dependencies": {
    "fastify": "^3.22.0",
    "fastify-mongodb": "^4.1.1",
    "fastify-nextjs": "^6.0.0",
    "fastify-static": "^4.4.2",
    "next": "11.1.2",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
```
server.js
```
const fastify = require('fastify')();
const fastifyNextjs = require('fastify-nextjs');
const dev = process.env.NODE_ENV !== 'production';
const customOption = {dev};
fastify.register(fastifyNextjs,customOption).after(()=>{
    console.log(fastify);
    fastify.next('/test');
});
fastify.listen(3000,'0.0.0.0',(err, address) => {
    if(err){
        throw err;
    };
    console.log(`Server listening on ${address}`);
});
```

bash
```bash
yarn run dev
```
TypeError: fastify.next is not a function

**Comment by AlfeeAeman** [comment]
any solution given for this?

**Comment by biryusal** [comment]
> any solution given for this?

the only one solution I've found - is to place **`.register(fastifyNext, { conf })`** higher than other _.register middlewares_
