### ISSUE TITLE
failure to set up when using fastify-cli boilerplate

### ISSUE THREAD

**Issue by bkyerv** [fastify/fastify-nextjs#407]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Could you please add to the documentation what needs to be done in order to use fastify-nextjs with fastify-cli generated boilerplate project structure? Any attempt to use fastify-cli with fastify-nextjs results in failure to run the server.

**Comment by Eomm** [comment]
What is the error?

**Comment by bkyerv** [comment]
Hello Eomm, there is no error, it just doesn't launch without throwing any error. Basically boilerplate project generated using fastify-cli works absolutely fine until I start trying to add fastify-nextjs plugin after which it just doesn't launch the server yet doesn't throw any error either. The way I add fastify-nextjs is I register this app in the root file app.js and attache an .after method passing a route to this method. I understand this somehow breaks the work of the boilerplate project. I also tried to add the plugin in a separate folder where all plugins are registered but that leads to the same outcome. My goal is quite simple: to set up fastify-nextjs plugin in a project generated by fastify-cli

**Comment by DonsWayo** [comment]
@bkyerv maybe the problem is the first launch with nextjs If you use typescript the tsconfig.json changes and modify some parts, one is the ``` "noEmit": true``` this makes unable to compile anymore and the ./dist folder is always the same (source of fastify cli runs).
you need to change to ``` "noEmit": false```.
