### ISSUE TITLE
Fastify hooks on the route opts type

### ISSUE THREAD

**Issue by stefee** [fastify/fastify-nextjs#432]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

This would allow to simplify the custom request properties example on the readme https://github.com/fastify/fastify-nextjs#custom-properties-on-the-request-object

Instead of needing a `register` with a prefix, you could add the hook on the `.next` call directly.

```ts
fastify.next('/hello', {
  onRequest: function (request, reply, done) {
    // define a custom property on the request
    request.raw.customProperty = { hello: "world" }
    // OR make the instance of fastify-redis available in the request
    request.raw.redisInstance = instance.redis
    done()
  }
});
```

### Motivation

Currently it is not possible (as far as I can tell?) to apply a hook to the routes handled by the next plugin only, _unless_ there is a route prefix like in the readme example.

### Example

```ts
fastify.next('*', {
  {
    onRequest: () => {
      // hook contents here
    },
  },
});
```

**Comment by stefee** [comment]
It looks like this feature already is implemented, but the type definition is incorrect.

**Comment by franky47** [comment]
I'm hitting a similar issue: I'd like to run the onRequest hook only for Next.js pages that actually have a server-side function attached to it (getServerSideProps, getStaticProps for ISR).

So far I can only register the onRequest hook globally (including all non-Next API routes handled by Fastify), or none at all.

Here's my attempt at encapsulating the onRequest hook:
```ts
import type {
  FastifyInstance,
  FastifyLoggerInstance,
  FastifyPluginAsync,
  FastifyReply,
  FastifyRequest,
  HookHandlerDoneFunction
} from 'fastify'
import fastifyNextJS from 'fastify-nextjs'
import fp from 'fastify-plugin'

declare module 'http' {
  interface IncomingMessage {
    fastify: FastifyInstance
    log: FastifyLoggerInstance
  }
}

const nextJsPlugin: FastifyPluginAsync<any> = async fastify => {
  const log = fastify.log.child({ scope: 'nextjs' })

  let serverRoutes: string[] = [
    // Declare routes that need to access the fastify server:
    '/ssr', // uses getServerSideProps
    '/isr' // uses getStaticProps with ISR
  ]

  await fastify
    .register(fastifyNextJS, {
      logLevel: 'warn'
    })
    .after()

  await fastify
    .register(async function nextJSServerRoutes(encapsulation) {
      encapsulation.addHook(
        'onRequest',
        function injectServerInNextJSRoute(
          request: FastifyRequest,
          _reply: FastifyReply,
          done: HookHandlerDoneFunction
        ) {
          request.raw.fastify = encapsulation
          request.raw.log = log
          done()
        }
      )
      serverRoutes.forEach(page => {
        encapsulation.next(page)
      })
    })
    .after()

  // Register the remaining Next.js routes
  fastify.next('/*')
}

export default fp(nextJsPlugin, {
  fastify: '3.x',
  name: 'nextjs-demo'
})
```

@stefee have you found a way to solve your issue ?

**Comment by stefee** [comment]
I found that encapsulating the `.next(‘*’)` in a plugin (with `.register`) fixed my issue - now the `onRequest` is only called for requests handled by Next.js.


I also have an early return in the `onRequest` handler for public static files:

```ts
const PUBLIC_FILE_PATHS = [
  '/_next/',
  '/static/',
  '/favicon.ico',
  '/robots.txt',
];
```

```ts
      const { url } = request;
      const isPublicFile = PUBLIC_FILE_PATHS.some((path) =>
        url.startsWith(path),
      );

      if (isPublicFile) {
        return;
      }
```

I was going to try to find a better way of doing this - maybe just disabling static file serving in the plugin and doing it with a separate plugin instead.

**Comment by franky47** [comment]
It did not occur to me to isolate the rest of the routes, it makes sense, however it doesn't work in my case as I only want the hook on a subset of Next.js pages.

FYI, I also had an issue with using `fastify-plugin`, which was hoisting the hook to the rest of my routes. Since it's not useful in my case (no shared decorators), the following worked for me without needing any encapsulation other than that provided by the plugin file:
```ts
import type {
  FastifyInstance,
  FastifyLoggerInstance,
  FastifyPluginAsync,
  FastifyReply,
  FastifyRequest,
  HookHandlerDoneFunction
} from 'fastify'
import fastifyNextJS from 'fastify-nextjs'

declare module 'http' {
  interface IncomingMessage {
    fastify: FastifyInstance
    log: FastifyLoggerInstance
  }
}

const nextJsPlugin: FastifyPluginAsync<any> = async fastify => {
  const log = fastify.log.child({ scope: 'nextjs' })

  let serverRoutes: string[] = [
    // Declare routes that need to access the fastify server:
    '/ssr', // uses getServerSideProps
    '/isr' // uses getStaticProps with ISR
  ]

  await fastify
    .register(fastifyNextJS, {
      logLevel: 'warn'
    })
    .after()

  serverRoutes.forEach(page => {
    fastify.next(page, {
      onRequest: function injectServerInNextJSRoute(
        request: FastifyRequest,
        _reply: FastifyReply,
        done: HookHandlerDoneFunction
      ) {
        request.raw.fastify = fastify
        request.raw.log = log
        done()
      }
    } as any)
  })

  // Register the remaining Next.js routes
  fastify.next('*')
}

export default nextJsPlugin
```

I'll see if I can open a PR to edit the types of the options passed to `.next()` to include anything accepted by `fastify.route()`.

> maybe just disabling static file serving in the plugin and doing it with a separate plugin instead.

How about using [`fastify-static`](https://github.com/fastify/fastify-static) to serve the `/public` directory ? That's what I'm planning on doing.

**Comment by mcollina** [comment]
A PR would be highly welcomed.
