### ISSUE TITLE
Unable to render _error page, renders 404 page instead

### ISSUE THREAD

**Issue by stefee** [fastify/fastify-nextjs#435]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.0

### Plugin version

7.0.0

### Node.js version

16.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6.1

### Description

The plugin uses `app.render` under the hood, which explicitly disallows rendering `_app`, `_document` and `_error` pages:

https://github.com/vercel/next.js/blob/e75361fd03872b097e817634c049b3185f24cf56/packages/next/server/base-server.ts#L1704

Attempting to render the `_error` path (as described in the readme) results in a 404 Not Found response.

> If you need to render with Next.js from within a custom handler (such as an error handler), use `reply.nextRender`
> 
> ```js
> app.setErrorHandler((err, req, reply) => {
>   reply.status(err.statusCode || 500)
>   return reply.nextRender('/_error')
> })
> ```

### Steps to Reproduce

See description.

### Expected Behavior

The plugin should either:

1. Decorate the request with the `app` instance, so that [`app.renderError`](https://github.com/vercel/next.js/blob/e75361fd03872b097e817634c049b3185f24cf56/packages/next/server/base-server.ts#L2336) can be called manually
2. Decorate fastify with a `reply.nextRenderError` which proxies the `app.renderError` similar to how `reply.nextRender` works

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by stefee** [comment]
Cheers - I think option 2 makes most sense specifically for this problem. Option 1 is a more general feature suggestion.

👉🏻  #436
