### ISSUE TITLE
Add support for http2

### ISSUE THREAD

**Issue by sqwerl** [fastify/fastify-nextjs#457]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add support for serving next.js with a HTTP2 using fastify

**Comment by mcollina** [comment]
I think it should work out of the box, isn't it?

**Comment by aryef** [comment]
No, this does not work out of the box. I get various errors
