### ISSUE TITLE
Plugin not working with option dev: true

### ISSUE THREAD

**Issue by makks129** [fastify/fastify-nextjs#464]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.3

### Plugin version

7.1.1

### Node.js version

16

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6.2

### Description

Throwing the following error when passing an option `{ dev: true }`:
```
Error: ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: /app/node_modules/fastify-nextjs/index.js. You may have forgotten to call 'done' function or to resolve a Promise
    at Timeout._onTimeout (/app/node_modules/avvio/plugin.js:123:19)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ERR_AVVIO_PLUGIN_TIMEOUT',
  fn: <ref *1> [Function: fastifyNext] {
    default: [Circular *1],
    fastifyNextjs: [Circular *1],
    [Symbol(skip-override)]: true,
    [Symbol(fastify.display-name)]: 'fastify-nextjs',
    [Symbol(plugin-meta)]: { fastify: '>=1.0.0', name: 'fastify-nextjs' }
  }
}
```

**
I'm not sure its relevant but SWC is disabled with `"presets": ["next/babel"]` in `.babelrc`

### Steps to Reproduce

```ts
import fastify from 'fastify';
import nextjs from 'fastify-nextjs';

export default fastify().register(nextjs, { dev: true });
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by makks129** [comment]
The problem was that nextjs needs more time to start up, so in dev mode I needed to add:
```ts

const fastifyOptions = isDev ? { pluginTimeout: 120_000 } : null;

export default fastify(fastifyOptions)
     .register(nextjs, { dev: isDev })
```

**Comment by Eomm** [comment]
Go for it
