### ISSUE TITLE
Promise may not be fulfilled with 'undefined' when statusCode is not 204

### ISSUE THREAD

**Issue by meotimdihia** [fastify/fastify-nextjs#47]
Example is working , but i got this warning in console output: 
`
{"level":50,"time":1545106522717,"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","pid":13839,"hostname":"DESKTOP-SAF118C","reqId":2,"err":{"type":"Error","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"Error: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at /mnt/c/sources/fastify/node_modules/fastify/lib/wrapThenable.js:18:34\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"v":1}
`

And i tried example from nextjs repo : https://github.com/zeit/next.js/tree/canary/examples/custom-server-fastify. Everything is good. 

it seems the problem at `reply.sent = true.`

**Comment by delvedor** [comment]
Hi! We are working on it: https://github.com/fastify/fastify-react/pull/46 and https://github.com/fastify/fastify/issues/1330.

**Comment by meotimdihia** [comment]
Thanks. I close this issue.

**Comment by millette** [comment]
I think this can be closed now.

**Comment by PabloSzx** [comment]
Did this error re-appeared again? 

```
] {"level":50,"time":1595051438703,"pid":5576,"hostname":"DESKTOP-8UM9NM1","reqId":10,"err":{"type":"FastifyError","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at C:\\Users\\pablo\\salmones_api\\node_modules\\fastify\\lib\\wrapThenable.js:30:30\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","name":"FastifyError","code":"FST_ERR_PROMISE_NOT_FULLFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204"}
```

```
    "fastify": "^3.1.1",
    "fastify-gql": "^5.1.0",
    "fastify-nextjs": "^5.0.3",
```

**Comment by Eomm** [comment]
> Did this error re-appeared? 
> 
> ```
> ] {"level":50,"time":1595051438703,"pid":5576,"hostname":"DESKTOP-8UM9NM1","reqId":10,"err":{"type":"FastifyError","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at C:\\Users\\pablo\\salmones_api\\node_modules\\fastify\\lib\\wrapThenable.js:30:30\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","name":"FastifyError","code":"FST_ERR_PROMISE_NOT_FULLFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204"}
> ```
> 
> ```
>     "fastify": "^3.1.1",
>     "fastify-gql": "^5.1.0",
>     "fastify-nextjs": "^5.0.3",
> ```

This issue is very old, please open a new one with a minimal exemple to reproduce

**Comment by nilaysaha** [comment]
yes error still appears for no reason: 
{"level":50,"time":1595423948211,"pid":7440,"hostname":"iot.oef.io","reqId":1,"err":{"type":"FastifyError","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at /home/ubuntu/projects/exams/medimaging/node_modules/fastify/lib/wrapThenable.js:30:30\n    at process._tickCallback (internal/process/next_tick.js:68:7)","name":"FastifyError","code":"FST_ERR_PROMISE_NOT_FULLFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204"}

**Comment by PabloSzx** [comment]
> yes error still appears for no reason:
> {"level":50,"time":1595423948211,"pid":7440,"hostname":"iot.oef.io","reqId":1,"err":{"type":"FastifyError","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n at /home/ubuntu/projects/exams/medimaging/node_modules/fastify/lib/wrapThenable.js:30:30\n at process._tickCallback (internal/process/next_tick.js:68:7)","name":"FastifyError","code":"FST_ERR_PROMISE_NOT_FULLFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204"}

v5.0.4 fixed it

**Comment by CodingPheonix** [comment]
error still appearing?

{"level":50,"time":1624191071402,"pid":60269,"hostname":"Adityas-MacBook-Pro.local","reqId":"req-1","err":{"type":"FastifyError","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at /Users/adityaagrawal/Documents/Projects/GKapp/node_modules/fastify/lib/wrapThenable.js:30:30\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","name":"FastifyError","code":"FST_ERR_PROMISE_NOT_FULFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204"}

**Comment by bkyerv** [comment]
> > yes error still appears for no reason:
> > {"level":50,"time":1595423948211,"pid":7440,"hostname":"iot.oef.io","reqId":1,"err":{"type":"FastifyError","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n at /home/ubuntu/projects/exams/medimaging/node_modules/fastify/lib/wrapThenable.js:30:30\n at process._tickCallback (internal/process/next_tick.js:68:7)","name":"FastifyError","code":"FST_ERR_PROMISE_NOT_FULLFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204"}
> 
> v5.0.4 fixed it

fifth version of what this has been fixed from? fastify itself is v3, no?

**Comment by SeLub** [comment]
{"level":50,"time":1639136817759,"pid":127578,"hostname":"pop-os","reqId":"req-6","err":{"type":"FastifyError","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at /home/Documents/progs/nodejs2021Q4-service/node_modules/fastify/lib/wrapThenable.js:30:30\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","name":"FastifyError","code":"FST_ERR_PROMISE_NOT_FULFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204"}

**Comment by climba03003** [comment]
Please open your own issue with reproducible example.
