### ISSUE TITLE
Q: is `noServeAssets` supposed to apply to both `/_next/data` and `/_next/static` ?

### ISSUE THREAD

**Issue by stefee** [fastify/fastify-nextjs#478]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The section on [asset serving](https://github.com/fastify/fastify-nextjs#assets-serving) in the readme led me to think that routes under `/_next/*` are "assets" i.e. static assets (and hence the `noServeAssets` will disable static asset serving via Next.js and allow me to serve using something like [`fastify-static`](https://github.com/fastify/fastify-static) instead).

I've since found that the `/_next/*` routes actually cover both dynamic (`/_next/data/*`) and static (`/_next/static/*`) routes.

I'm unsure if this was simply a misunderstanding on my part OR a misunderstanding on the part of the author.

I was wondering if the option for `noServeAssets` should really be scoped to `_next/static` only and not `_next/data` - I would also look to improve the readme either way to clear up the initial confusion.

Also worth noting, I'm not sure if the `_next/data` and `_next/static` are a documented part of the Next.js API that we can rely on or an internal detail that might break in a future minor/patch release.

**Comment by mcollina** [comment]
Thanks for reporting. Unfortunately, I don't have a good answer for your question. If you figure it out and would like to send a PR to fix or improved the docs, it'd be amazing!

**Comment by stefee** [comment]
I’ll see if I can make it clearer on Next.js side
