### ISSUE TITLE
Rename to fastify-nextjs

### ISSUE THREAD

**Issue by TheAifam5** [fastify/fastify-nextjs#49]
Hey!

I know, there is already an issue #29 but still, the package/repository should be named as `fastify-next` or `fastify-nextjs` (i prefer the @tsnieman name) because:
- The package/repository integrates only with Next.Js.
- The package/repository does not integrate with barebone React environments.
- The package/repository name barely says that is about React, not Nextjs which is misleading.
- The current package/repository name could be used to provide an *real* integration with barebone react environments which have nothing with Next.JS to do.

Regards,
TheAifam5

**Comment by mcollina** [comment]
@delvedor @cemremengu I'm actually thinking that this is a good idea. Wdyt?

**Comment by cemremengu** [comment]
Considering the confusion before and this argument (which I think is strong) I am +1. 

How will the renaming process be? I hope it won't be too disruptive

**Comment by mcollina** [comment]
We just:

a. rename this repository
b. change package.json name to `fastify-nextjs`.
c. publish on npm with version 1.0.0
d. deprecate fastify-react (there is a command in npm for this)

**Comment by cemremengu** [comment]
If @delvedor agrees too I can take over this task

**Comment by delvedor** [comment]
I think that the README states pretty well what this plugin is doing.
`React server side rendering support for Fastify with Next Framework.`

But since this is creating so much confusion let's change it.

**Comment by cemremengu** [comment]
v1.0.0 published https://www.npmjs.com/package/fastify-nextjs
