### ISSUE TITLE
Tailwind CSS compiler not working in fastify-nextjs

### ISSUE THREAD

**Issue by ivanjeremic** [fastify/fastify-nextjs#492]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Tailwind CSS has in the Documentation a installation guide for Next.js and following it in fastify-nextjs does not give me any styles, do I need to add additional settings to my server to trigger the tailwindcss compiler?

**Comment by darkgl0w** [comment]
Hello, @ivanjeremic.

In order to use `tailwindcss` you need to :

1. initialize your project :
```sh
npm install fastify fastify-nextjs
npm install -D @types/node @types/react typescript
```
2. create `index.js`:
```js
'use strict';

const Fastify = require('fastify');
const fastifyNextjs = require('fastify-nextjs');

const fastify = Fastify();

fastify.register(fastifyNextjs).after(() => {
  fastify.next('/home');
});

fastify.listen({ host: '127.0.0.1', port: 3000 });
```
3. follow [this guide](https://tailwindcss.com/docs/guides/nextjs) from step 2 to step 4
4. then override Next.js App by creating `./pages/_app.tsx` (here I use Typescript but you can do it with plain JavaScript if you want):
```tsx
import '../styles/globals.css'
import type { AppProps } from 'next/app'

function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}

export default MyApp
```
5. create `./pages/home.tsx` :
```tsx
export default function home() {
  return (
    <div className='bg-red-500'>
      <h1>Hello !</h1>
    </div>
  );
}
```
6. run your server with `node index.js` and open http://127.0.0.1:3000/home. 

Et voilà.

[Next.js documentation use cases](https://nextjs.org/docs/advanced-features/custom-app) apply to `fastify-nextjs` too.

**Comment by ivanjeremic** [comment]
> Hello @ivanjeremic.
> 
> In order to use `tailwindcss` you need to :
> 
> 1. initialize your project :
> 
> ```shell
> npm install fastify fastify-nextjs
> npm install -D @types/node @types/react typescript
> ```
> 
> 2. create `index.js`:
> 
> ```js
> 'use strict';
> 
> const Fastify = require('fastify');
> const fastifyNextjs = require('fastify-nextjs');
> 
> const fastify = Fastify();
> 
> fastify.register(fastifyNextjs).after(() => {
>   fastify.next('/home');
> });
> 
> fastify.listen({ host: '127.0.0.1', port: 3000 });
> ```
> 
> 3. follow [this guide](https://tailwindcss.com/docs/guides/nextjs) from step 2 to step 4
> 4. then override Next.js App by creating `./pages/_app.tsx` (here I use Typescript but you can do it with plain JavaScript if you want):
> 
> ```tsx
> import '../styles/globals.css'
> import type { AppProps } from 'next/app'
> 
> function MyApp({ Component, pageProps }: AppProps) {
>   return <Component {...pageProps} />
> }
> 
> export default MyApp
> ```
> 
> 5. create `./pages/home.tsx` :
> 
> ```tsx
> export default function home() {
>   return (
>     <div className='bg-red-500'>
>       <h1>Hello !</h1>
>     </div>
>   );
> }
> ```
> 
> 6. run your server with `node index.js` and open http://127.0.0.1:3000/home.
> 
> Et voilà.
> 
> [Next.js documentation use cases](https://nextjs.org/docs/advanced-features/custom-app) apply to `fastify-nextjs` too.

Is the use of typescript necessary? I currently did everything like you described except using typescript (I'm on an ESM project) and only my tailwind.config is a `.cjs` because the config does not support ESM yet.

**Comment by darkgl0w** [comment]
No I used typescript but as I said you can achieve the same result using plain JavaScript

**Comment by ivanjeremic** [comment]
> ```shell
> npm install -D @types/node @types/react typescript
> ```

It does not work, my project is MJS I think tailwind doesn't like that

**Comment by darkgl0w** [comment]
> > ```shell
> > npm install -D @types/node @types/react typescript
> > ```
> 
> It does not work, my project is MJS I think tailwind doesn't like that

skip this part.

- use `./pages/_app.js` or `jsx` instead of `./pages/_app.tsx` with :
```js
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}

export default MyApp
```
- rename as `./pages/home.js` or `jsx` instead of `./pages/home.tsx`

**Comment by darkgl0w** [comment]
@ivanjeremic is it ok with these changes ? can I close this issue ?

**Comment by ivanjeremic** [comment]
> @ivanjeremic is it ok with these changes ? can I close this issue ?

I think the problem is that I need to have ```
 |── postcss.config.cjs
└── tailwind.config.cjs
```

because I use ESModules `"type": "module",` and config files do not work with ESM for now but I can force rename them to cjs that hack works normally but for some reason not with fastify-nextjs

**Comment by darkgl0w** [comment]
Then just rename your files and add cjs extension to `tailwind.config.js` content property

**Comment by ivanjeremic** [comment]
> Then just rename your files and add cjs extension to `tailwind.config.js` content property

I already use `.cjs` for my config files. But it is not working.

**Comment by darkgl0w** [comment]
As a workaround you can do this :

- Run this command :
```sh
npx tailwindcss -c tailwind.config.cjs -i ./styles/globals.css -o ./styles/main.css --watch
```
- Inside `./pages/_app.jsx` change `global.css` import with `main.css`

It should work.
NB: this seems to be a limitation of tailwindcss with esm :/

**Comment by ivanjeremic** [comment]
> ```shell
> npx tailwindcss -c tailwind.config.cjs -i ./styles/globals.css -o ./styles/main.css --watch
> ```

Yep that works thanks, hope library authors will take ESM more serious in the future.

**Comment by climba03003** [comment]
Looking through the conversation, I believe nothing can do with `fastify-nextjs`. So, I am closing the issue.
