### ISSUE TITLE
custom root for fastify-nextjs

### ISSUE THREAD

**Issue by ivanjeremic** [fastify/fastify-nextjs#497]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I know how to create a custom root in next.js using the `next.cofig` the same works here but what I want is to ship my whole `fastify-nextjs` User Interface as an fastify plugin available on NPM, so the user of this plugin should register the fastify plugin and get automatically the UI that ships with it, Currently this does not work when shipped as an npm package because it keeps looking at the project root, is there any workaround?

**Comment by ivanjeremic** [comment]
I now found that I can do that with custom nextjs option ` { dir: "./customPath" }` however it grabs on my production node server still the jsx files and I get `You may need an appropriate loader to handle this file type` it seems like I'm not using the production Nextjs version how do I start the production version of fastify-nextjs on a production server? Thanks

**Comment by Eomm** [comment]
You need to set the node env var:

https://github.com/fastify/fastify-nextjs/blob/master/index.js#L16

```
fastify
  .register(require('fastify-nextjs'), { dev: false })
  .after(() => {
    fastify.next('/hello')
  })
```

**Comment by ivanjeremic** [comment]
> You need to set the node env var:
> 
> https://github.com/fastify/fastify-nextjs/blob/master/index.js#L16
> 
> ```
> fastify
>   .register(require('fastify-nextjs'), { dev: false })
>   .after(() => {
>     fastify.next('/hello')
>   })
> ```

Thanks works.
