### ISSUE TITLE
Assignment for options misplaced in plugin (Next.js 7.0.3)

### ISSUE THREAD

**Issue by jimmiehansson** [fastify/fastify-nextjs#52]
**Description**
The current state of implementation of constructing the options object for Next to read on its construct is passed incorrectly.

```js
  const app = Next(Object.assign(
    { dev: process.env.NODE_ENV !== 'production' },
    options
  ))
```

**Environment**
fastify 1.13.3
fastify-nextjs 4.0.0
next 7.0.3

**Effect**
The Next construct is not aware of the current environment state, getting locked into development mode.

**Resolution**
Construct object by returning chain in right order

```js
const app = Next(Object.assign({}, options, { dev: process.env.NODE_ENV !== 'production' }))
```

**Comment by cemremengu** [comment]
Thanks @jimmiehansson ! Would you like to send a PR with a unit test ?

**Comment by jimmiehansson** [comment]
Will get to this in the upcoming days, having a handful atm.

**Comment by jimmiehansson** [comment]
@cemremengu Added tests finally
