### ISSUE TITLE
Using fastify-nextjs with fastify-cookie

### ISSUE THREAD

**Issue by kokisalex** [fastify/fastify-nextjs#54]
Hi, i have module  fastify-cookie and fastify-nextjs. I need support cookies for context next pages. Is that possible without parsing cookies again in next request?

```
export default class Main extends React.Component {
  static async getInitialProps(context) {
    const main =  await fetch.get('/api/main')
    return {main}
  }
  render() {
    <div>{this.props.main}</div>
  }
}
```

**Comment by mcollina** [comment]
I don't understand. You mean the cookies returned from `/api/main`?

**Comment by kokisalex** [comment]
No, fastify parses cookies and puts them in to `request.cookies`. In nextjs there's a raw request without parsed cookies in `context`. I need to pass some cookies to `context` in `getInitialProps`.

```
fastify.register(require('fastify-cookie'))

fastify.next('/hello', (app, req, reply) => {
  const additionalParams = req.cookies.myCookie;
  // pass additional params to render
  app.render(req.raw, reply.res, '/hello', req.query, {}, additionalParams)
})

// next page component
static async getInitialProps(context) {
    // read additionalParams here from context
}
```

**Comment by mcollina** [comment]
Is the above code not working? Can you send a PR with a failing test?

**Comment by kokisalex** [comment]
ok

**Comment by kokisalex** [comment]
I'm sorry. The issue is not actual now. I found that the method in nextjs doesn't allow to send anything
