### ISSUE TITLE
Fastify v4 error: "under-pressure - expected '3.x' fastify version, '4.0.0' is installed"

### ISSUE THREAD

**Issue by rriski** [fastify/fastify-nextjs#549]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Plugin version

8.0.0

### Node.js version

16.13.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.1

### Description

When using @fastify/nextjs with the underPressure option an unexpected plugin version error is thrown.

### Steps to Reproduce

1. Use fastify v4 and plugin v8
2. Configure plugin with any `underPressure` options
3. Error is thrown due to https://github.com/fastify/fastify-nextjs/blob/6449bfd7a50744dc862faaba910fdd8edba48c56/index.js#L13, and https://github.com/fastify/fastify-nextjs/blob/6449bfd7a50744dc862faaba910fdd8edba48c56/package.json#L49

### Expected Behavior

No error is thrown when using `underPressure` options.

**Comment by Fdawgs** [comment]
`under-pressure` needs to be replaced with the latest version of `@fastify/under-pressure`, would you like to open a PR to tackle this?

**Comment by rriski** [comment]
Sure thing! Here: https://github.com/fastify/fastify-nextjs/pull/550

**Comment by mcollina** [comment]
Unfortunately I had to reopen this as v8 is meant to support Fastify v3 and this module was not ported to Fastify v4 yet (blocked by #555 and #557)
