### ISSUE TITLE
Update to Fastify v4

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-nextjs#557]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently the update to Fastify v4 is blocked by latest Next.js being incompatible with this module testing approach (#555).

After that is solved, we would need to update this module to Fastify v4.

**Comment by mcollina** [comment]
This is currently blocked by https://github.com/fastify/fastify-nextjs/issues/555. Essentially it needs work, help and love.

**Comment by stefee** [comment]
See comment https://github.com/fastify/fastify-nextjs/issues/555#issuecomment-1200237882

**Comment by drakhart** [comment]
Since #555 is no longer a blocker I'll try my best at this issue too. 🤞

**Comment by Uzlopak** [comment]
@drakhart 
see #589

**Comment by drakhart** [comment]
> @drakhart see #589

Nice! 👏
