### ISSUE TITLE
It takes 10s to restart hello world app. 

### ISSUE THREAD

**Issue by meotimdihia** [fastify/fastify-nextjs#57]
I know this is not fastify's problem but I think we can't use nextjs while developing backend code. 
We need 1 way to reload server code but not to restart fastify server.

**Comment by Eomm** [comment]
Hi,
do you mean the hello world of the read me file?
In case could you add more information how you run the application?

**Comment by meotimdihia** [comment]
Hi, this is my results:  

command: `node test1.js` **5s to start:** 

```js
const fastify = require('fastify')()

fastify
  .register(require('fastify-nextjs'))
  .after(() => {
    fastify.next('/hello')
  })

fastify.listen(3000, err => {
  if (err) throw err
  console.log('Server listenging on http://localhost:3000')
})
```

command: `fastify start --watch --ignore-watch="node_modules .git logs .vscode .next dist pages" -l debug -P test2.js`  **10s to start**
```js
'use strict'

const path = require('path')
const AutoLoad = require('fastify-autoload')

module.exports = function (fastify, opts, next) {
  // Place here your custom code!
fastify.register(require('fastify-nextjs'))
  // Do not touch the following lines

  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'plugins'),
    options: Object.assign({}, opts)
  })

  // This loads all plugins defined in services
  // define your routes in one of these
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'services'),
    options: Object.assign({}, opts)
  })

  // Make sure to call next when done
  next()
}
```

command: `node test3.js`  **1s to start**

```js
// Require the framework and instantiate it
const fastify = require('fastify')({
  logger: true
})

// Declare a route
fastify.get('/', function (request, reply) {
  reply.send({ hello: 'world' })
})

// Run the server!
fastify.listen(3000, function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${address}`)
})
```

**Comment by mcollina** [comment]
Which operating system are you in? Even 1s seems exceptionally slow.

I’m not super familiar with next, maybe we are missing some config for caching stuff.

**Comment by meotimdihia** [comment]
My OS is windows 10. 
Yes, I think its nextjs problem. I just ask if anyone met/knew solutions:

![2019-03-28_18-23-54](https://user-images.githubusercontent.com/300961/55154312-0ce0ba80-5187-11e9-8bec-ed29f4c5f4b3.gif)

**Comment by meotimdihia** [comment]
But its strange too, if I start standalone nextjs-server, its just take 1-2s.

**Comment by jimmiehansson** [comment]
Hey @meotimdihia 

I haven't experienced any issues with this, but then again I'm not a Windows platform user either

This could be related to the services racing each other in the start.
Could you perhaps add a `next.config.js` and enable explicit `dev:enable` with logging in fastify. (You can pass this to the fastify object) 

```js
const opts = {
  logger: true
}
const fastify = require('fastify')(opts);
```

Additionally during the bootstrap if you can't get any further verbosity, you could monitor the ports being listened to using `watch -n1 "lsof -i :3000"` or replace with the internal port used by the next socket. This could possibly point us in the right direction on which service might be at fault in the bootstrap sequence

**Comment by StarpTech** [comment]
@meotimdihia what are your computer specs?
On the first sight it looks reasonable to me because in `dev` mode next.js will start with compiling your application and bootstrap cache etc.. On my machine (SSD, AMD Ryzen 5 2600X (12) @ 3.600G) it takes up to 5sec. If you want to avoid it you have to  split your api and frontend application in two processes or starting your next.js server in production mode.

**Comment by jimmiehansson** [comment]
I can second this, I've compiled a large sized project using this plugin with a ~6s bootstrap on a nvme, i7. Keep in mind though that this is a large dev build

**Comment by meotimdihia** [comment]
Hi, my CPU is Xeon E3-1231 v3 @3.40Ghz.  
According to, @jimmiehansson  @StarpTech, seems at least, we still need 5-6s to compile => its hard to code and debug.  

Currently, I am using Webpack hot module reload for fastify+nextjs to solve this problem.

**Comment by StarpTech** [comment]
@meotimdihia I don't understand your issue. Next.js is shipped with HMR already. If you restart your application on every change, webpack has to compile it again and again. If you want to save time you should run your api in a separate process.

**Comment by meotimdihia** [comment]
@StarpTech next.js just reload when we modified files in `pages` directory, while we need to work with other directories. Example: add new routes, fix middleware, .... aren't working with next.js's HMR.

**Comment by StarpTech** [comment]
Then don't put your api under the nextjs directories. Put your api in a directory called "server" next to the "pages".

**Comment by meotimdihia** [comment]
I want to clarify this again: 
> I don't understand your issue. Next.js is shipped with HMR already. If you restart your application on every change, Webpack has to compile it again and again and this takes time.  

After use Webpack HMR, I don't need to restart Fastify server or Next.js.  

> If you want to save time you should run your API in a separate process.  

Thanks for the suggestion, I will try this - my head is still same logic as using PHP framework, I don't completely understand node.js ways.

**Comment by meotimdihia** [comment]
I close issues, 
[Next 9](https://nextjs.org/blog/next-9) introduced: Dynamic Route, API Routes. May change how we will work with next.js.

**Comment by donburks** [comment]
Running into a similar issue. Even on a nearly new MBP, it's taking nearly 6s to compile my app in dev mode, and in production, I'm getting `ERR_AVVIO_PLUGIN_TIMEOUT` errors and my build fails entirely.

```
Error: ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: /usr/src/app/node_modules/fastify-nextjs/index.js
    at Timeout._onTimeout (/usr/src/app/node_modules/avvio/plugin.js:81:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ERR_AVVIO_PLUGIN_TIMEOUT',
  fn: [Function: fastifyNext] {
    [Symbol(skip-override)]: true,
    [Symbol(fastify.display-name)]: 'fastify-nextjs',
    [Symbol(plugin-meta)]: { fastify: '>=1.0.0', name: 'fastify-nextjs' }
  }
}
```

**Comment by ilyaviache** [comment]
@donburks You can change **pluginTimeout** time to avoid this error
https://github.com/fastify/fastify/blob/master/docs/Server.md#plugintimeout

**Comment by StarpTech** [comment]
There is a big misunderstanding. Fastify-nextjs starts a new next.js instance and wire up what is needed to run and develop a next.js app. 2-5 is common depending on the computer specs and project complexity. If you are working side-by-side on an api endpoint you have to restart your api, EVERYTIME. To avoid this you should run your api and nextjs instance in separate processes. In that way you can avoid restarting your whole application if you are working on none nextjs relevant pages.

For development you would run then two fastify instances.

Btw: Check your requirements at first. In 99% usecases your font need a custom server in nextjs. They even support dynamic routes.

**Comment by donburks** [comment]
@ilyaviache - The last line of my post indicates that I have already tried doing this. And to @StarpTech 's point, this NextJS app is just for the front-end, the API is running in a fully separate instance.

**Comment by StarpTech** [comment]
@donburks How is it then related to fastify?

**Comment by StarpTech** [comment]
@donburks Please post a fully reproducible example otherwise we can't help.

**Comment by atzcl** [comment]
@donburks In the development phase, nextjs needs time to perform webpack related work, so you need to set a longer pluginTimeout
