### ISSUE TITLE
fastify.next() is not a function

### ISSUE THREAD

**Issue by AlfeeAeman** [fastify/fastify-nextjs#571]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

**Comment by jsumners** [comment]
Sorry. I thought this was a different repo. However, you really should provide more information. A minimal reproduction is usually needed.

**Comment by AlfeeAeman** [comment]
this package is not supported for fastify 4.x.x version

**Comment by mcollina** [comment]
This module is not compatible with Fastify v4: https://github.com/fastify/fastify-nextjs/issues/557. Moreover that issue is blocked.
