### ISSUE TITLE
How to use opts? Confused about next: property

### ISSUE THREAD

**Issue by msheakoski** [fastify/fastify-nextjs#58]
I saw that when defining a route, you can pass custom options to restrict the "method" and "schema" which are explained in the Fastify docs, but there is another required option, "next", that I do not understand: https://github.com/fastify/fastify-nextjs/blob/868056ea972717687ac60e335b2477518e834557/index.d.ts#L24-L34
According to the definition, it is supposed to a URL object, but I have no idea what this value should be or why it is required?

For example:
```javascript
const schema = {querystring: {name: {type: "string"}}};
server.next("/hello/:name", {method: "GET", schema, next: ?????}, (next, req, reply) => {
    return next.render(req.raw, reply.res, "/hello", {name: req.params.name});
});
```

**Comment by Eomm** [comment]
Hi,
docs are not clear enough for that setting (an example is missing) so a PR would be great to improve it.

Anyway, that type describes the next decorator:

https://github.com/fastify/fastify-nextjs/blob/868056ea972717687ac60e335b2477518e834557/index.js#L17

And the next field is given "as is" to the next-app here:

https://github.com/fastify/fastify-nextjs/blob/868056ea972717687ac60e335b2477518e834557/index.js#L54

So the parameter you can put there, are standard next params for the `app.render` function.

Maybe the typing for `next:` is wrong, IDK this detail: looking the code it must be an object.
Looking the type it must be as this:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/80d9c48f2d66477c2590413b4e067b62a0cd52f8/types/next-server/router.d.ts

**Comment by msheakoski** [comment]
Thank you for your reply, @Eomm. I did some further research and discovered a few problems with the typings:

1. The "next" opt should be optional and also probably renamed to parsedUrl so that it matches the Next.js code: https://github.com/zeit/next.js/blob/c9d599b69864f4a6c08cada4d0c9733cc630ddc4/packages/next-server/server/next-server.ts#L253-L259

2. The "next()" method that this plugin creates should not be restricted to returning "void" https://github.com/fastify/fastify-nextjs/blob/868056ea972717687ac60e335b2477518e834557/index.d.ts#L24-L34 because it might be defined as an async handler (https://www.fastify.io/docs/latest/Routes/#async-await), in which case you are required to return a value !== undefined: https://github.com/fastify/fastify-nextjs/blob/868056ea972717687ac60e335b2477518e834557/index.js#L50-L52

**Comment by msheakoski** [comment]
On second thought, I am not even sure if next/parsedUrl should even exist in opts because the URL is already parsed by Fastify prior to the default app.render() handler defined in this plugin being invoked: https://github.com/fastify/fastify-nextjs/blob/868056ea972717687ac60e335b2477518e834557/index.js#L54

If you provide your own callback, the default app.render() handler never runs, so you are free to provide whatever value you want for the parsedUrl arg of app.render(). If you do not provide it, Next.js will parse it from request.raw regardless.
