### ISSUE TITLE
Getting FastifyDeprecation: Modifying the "reply.sent" property is deprecated. Use the "reply.hijack()" method instead.

### ISSUE THREAD

**Issue by SimenB** [fastify/fastify-nextjs#609]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.5.3

### Plugin version

9.1.0

### Node.js version

16.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.5.1

### Description

Not sure why I haven't seen this error before, https://github.com/fastify/fastify/pull/3140 landed a long time ago and this repo upgraded to v4 a couple of weeks ago...

### Steps to Reproduce

Run `node examples/example.js` in this very repo (as of current HEAD f93534956005468fcb94f809ca29b3003870a1de) and navigate to `http://localhost:3000/hello`

### Expected Behavior

No deprecation warning

**Comment by mcollina** [comment]
https://github.com/fastify/fastify-nextjs/blob/master/index.js#L91 and https://github.com/fastify/fastify-nextjs/blob/master/index.js#L105 should be replaced.

**Comment by SimenB** [comment]
Yeah, I've sent #610 🙂
