### ISSUE TITLE
Can you add an example for Assets serving in the readme ?

### ISSUE THREAD

**Issue by kangchals** [fastify/fastify-nextjs#636]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I just want to add robot.txt on the next app but

I do not know where to put the file.

I checked it on the source code but https://github.com/fastify/fastify-nextjs/blob/master/index.js#L36

I am kind of new to the fastify so I still need some help. 

Thank you in advance.

**Comment by climba03003** [comment]
You should not use `nextjs` to serve `robot.txt`.
Create a dedicated route to response with `/robot.txt`.

```js
fastify.get('/robot.txt', function(request, reply) {
  reply.type('text/plain').send("User-agent: *\nAllow: /")
})

**Comment by climba03003** [comment]
If you really want to serve it. You may try to follow the [`nextjs` guide](https://nextjs.org/learn/seo/crawling-and-indexing/robots-txt)
Put the file inside `public` folder.

**Comment by kangchals** [comment]
@climba03003 Thank you for quick reply. 

Your help is working well.

I just want to know more for the future.
How about images? how to get some images in the next app?

**Comment by kangchals** [comment]
I put image below paths but none of them are working

/public
/src/public
/src/pages -> nextjs page folder
/src/_next/public

http://127.0.0.1:7000/testFile.png
{"message":"Route GET:/testFile.png not found","error":"Not Found","statusCode":404}

**Comment by climba03003** [comment]
The `html` serve by `nextjs` should be requesting `/_next/static/testFile.png`.
Are you querying the actual path using browser?

**Comment by kangchals** [comment]
Thank you for your help.
I just want to summary below for others

/public/testFile.png 
/src/pages -> nextjs page folder

in .tsx
`<Image src="/testFile.png" width="100" height="100" />`
