### ISSUE TITLE
drop node 14 support?!

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify-nextjs#759]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

it seems that next is not node14 compatible. We should consider dropping node14 support.

**Comment by climba03003** [comment]
It just support only because `node@14` EOL.
Interestingly, it doesn't consider itself as breaking change.
https://github.com/vercel/next.js/pull/48903

**Comment by Uzlopak** [comment]
@Fdawgs 

without a workflow which does not have node 14, we can not upgrade next.

**Comment by Fdawgs** [comment]
@mcollina  Are we able to drop Node 14, 3or do plugins have to adhere to the [main repo's LTS](https://www.fastify.io/docs/latest/Reference/LTS/) and continue to support 14 as long as the main repo does?

**Comment by Eomm** [comment]
I would just bump a new major of this plugin that does not support the nodejs14 version.

I think we did it already in past

**Comment by Uzlopak** [comment]
The issue is the workflow. The centralized workflow has not the capability to disable node 14.

**Comment by Fdawgs** [comment]
Closed by #763
