### ISSUE TITLE
Unable to read Body of POST

### ISSUE THREAD

**Issue by hybaken** [fastify/fastify-nextjs#87]
## 🐛 Bug Report

Body is never presented in context.req

## To Reproduce

1. Create POST page.
2. Send POST request to this page
3. Render the data in body

```js

export async function getServerSideProps(context) {
    let body = ''
    let req = context.req
   console.log(context.req)

    req.on('data', chunk => {
        console.log('1')
    })
    req.on('readable', function() {
        console.log('2')
    })
    req.on('end', function() {
        console.log('3')
    })

    return {
        props: {payment: body}
    }
}

```

## Expected behavior

context.req.body is not null

```js

```

## Your Environment

- *node version*: v12.3.1
- *fastify version*: >=^2.0.0
- *os*: Mac

**Comment by Eomm** [comment]
I don't know who `context.req` is: could you add a complete reproducible example that we can run just with `node index.js`?

**Comment by heisonyee** [comment]
req in context is an **IncomingMessage** instance but not a **FastifyRequest**, so req does not have body  property.  Hope it may help. @hybaken
