### ISSUE TITLE
fastify.next is not a function

### ISSUE THREAD

**Issue by puvi034** [fastify/fastify-nextjs#88]
#### You have already researched for similar issues?
Yes. I searched in the issue list and could n't find any.

#### Are you sure this is an issue with the fastify or are you just looking for some help?
 The issue seem to be in fastify-nextjs plugin.

#### Steps to reproduce.

1. clone https://github.com/fastify/fastify-nextjs.git
2. `cd fastify-nextjs && npm install`
2. run `npm run dev`

node version: v12.16.1
npm : 6.13.4

Error:
![image](https://user-images.githubusercontent.com/3928039/82719074-3480c500-9c5c-11ea-99c8-5aef3071c160.png)

If you have issues with the [fastify.io](https://www.fastify.io) site, please open an issue [here](https://github.com/fastify/website/issues).

**Comment by puvi034** [comment]
This issue seem to be a timeout issue and by default fastify wait for 10 secs. Changed timeout period and it started working.

**Comment by nonsensecodes** [comment]
@puvi034 how did you change the timeout period? I’m running into the same issue.

**Comment by Eomm** [comment]
The timeout is the plugin one: https://www.fastify.io/docs/latest/Server/#plugintimeout

**Comment by wolfejw86** [comment]
For what it's worth I'm not seeing this as related to a timeout.  I get this behavior immediately when setting `NODE_ENV=production`.  Has anyone come across this / figured out a way to solve it?

**Comment by sbfkcel** [comment]
> The timeout is the plugin one: https://www.fastify.io/docs/latest/Server/#plugintimeout
I extended the plug-in loading time and it did solve it.
